-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- NEVERTHELESS - Edited to provide a View instead of a Table.
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP VIEW IF EXISTS `lalg_cms_user`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new View
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * lalg_cms_user
-- *
-- * View onto Drupal users_field_data Table
-- *
-- *******************************************************/
SET @civi_db = DATABASE();
SET @cms_db = CONCAT(LEFT(@civi_db, LENGTH(@civi_db) -1), 'd');

SET @sql = CONCAT('
  CREATE OR REPLACE VIEW lalg_cms_user AS
  SELECT a.id AS contact_id, c.uid, c.name, c.mail, c.login, c.access 
  FROM ', @civi_db, '.civicrm_contact AS a 
  JOIN ', @civi_db, '.civicrm_uf_match AS b on a.id = b.contact_id 
  JOIN ', @cms_db, '.users_field_data AS c ON b.uf_id = c.uid;');

PREPARE stmt FROM @sql;
EXECUTE stmt;

