<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from lalg-civi-search/xml/schema/CRM/LalgCiviSearch/LalgCmsUser.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:9ff546cbc66ae4bec60d8200a876de42)
 */
use CRM_LalgCiviSearch_ExtensionUtil as E;

/**
 * Database access object for the LalgCmsUser entity.
 */
class CRM_LalgCiviSearch_DAO_LalgCmsUser extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'lalg_cms_user';

  /**
   * Primary key field(s).
   *
   * @var string[]
   */
  public static $_primaryKey = [];

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique LalgCmsUser ID
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $uid;

  /**
   * FK to Contact
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contact_id;

  /**
   * Login User Name
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $name;

  /**
   * Email Address
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $mail;

  /**
   * Timestamp of last login
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $login;

  /**
   * Timestamp of last Access
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $access;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'lalg_cms_user';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Lalg Cms Users') : E::ts('Lalg Cms User');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contact_id', 'civicrm_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'uid' => [
          'name' => 'uid',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Uid'),
          'description' => E::ts('Unique LalgCmsUser ID'),
          'required' => TRUE,
          'where' => 'lalg_cms_user.uid',
          'table_name' => 'lalg_cms_user',
          'entity' => 'LalgCmsUser',
          'bao' => 'CRM_LalgCiviSearch_DAO_LalgCmsUser',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contact ID'),
          'description' => E::ts('FK to Contact'),
          'where' => 'lalg_cms_user.contact_id',
          'table_name' => 'lalg_cms_user',
          'entity' => 'LalgCmsUser',
          'bao' => 'CRM_LalgCiviSearch_DAO_LalgCmsUser',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => NULL,
        ],
        'name' => [
          'name' => 'name',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Name'),
          'description' => E::ts('Login User Name'),
          'where' => 'lalg_cms_user.name',
          'table_name' => 'lalg_cms_user',
          'entity' => 'LalgCmsUser',
          'bao' => 'CRM_LalgCiviSearch_DAO_LalgCmsUser',
          'localizable' => 0,
          'add' => NULL,
        ],
        'mail' => [
          'name' => 'mail',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Mail'),
          'description' => E::ts('Email Address'),
          'where' => 'lalg_cms_user.mail',
          'table_name' => 'lalg_cms_user',
          'entity' => 'LalgCmsUser',
          'bao' => 'CRM_LalgCiviSearch_DAO_LalgCmsUser',
          'localizable' => 0,
          'add' => NULL,
        ],
        'login' => [
          'name' => 'login',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Login'),
          'description' => E::ts('Timestamp of last login'),
          'where' => 'lalg_cms_user.login',
          'table_name' => 'lalg_cms_user',
          'entity' => 'LalgCmsUser',
          'bao' => 'CRM_LalgCiviSearch_DAO_LalgCmsUser',
          'localizable' => 0,
          'add' => NULL,
        ],
        'access' => [
          'name' => 'access',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Access'),
          'description' => E::ts('Timestamp of last Access'),
          'where' => 'lalg_cms_user.access',
          'table_name' => 'lalg_cms_user',
          'entity' => 'LalgCmsUser',
          'bao' => 'CRM_LalgCiviSearch_DAO_LalgCmsUser',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, '_user', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, '_user', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
